Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/maartenpeels/Projects/polarsteps-slack/polarsteps
      Runtime: python3.9
      Architectures:
        - x86_64