AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Slack bot to track Polarsteps journey

Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Type: String
    Default: dev
  PolarstepsTripId:
    Type: String
  SlackOAuthToken:
    Type: String
  SlackChannelId:
    Type: String
  PolarstepsCookie:
    Type: String

Resources:
  PolarstepsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: polarsteps/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 300
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          POLARSTEPS_TRIP_ID: !Ref PolarstepsTripId
          SLACK_OAUTH_TOKEN: !Ref SlackOAuthToken
          SLACK_CHANNEL_ID: !Ref SlackChannelId
          POLARSTEPS_COOKIE: !Ref PolarstepsCookie
      Events:
        GetItems:
          Type: Api
          Properties:
            Path: /
            Method: get
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: cron(0 8 * * ? *) # Every day at 8:00 UTC
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
                - ssm:GetParametersByPath
                - ssm:PutParameter
              Resource:
                - arn:aws:ssm:*:*:parameter/*

  LastExecutionTimeParamater:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/polarsteps/lastExecutionTime/${Environment}"
      Type: String
      Value: '0'
