AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Slack bot to track Polarsteps journey

Globals:
  Function:
    Timeout: 3

Resources:
  PolarstepsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: polarsteps/
      Handler: app.lambda_handler
      Runtime: python3.9
